package com.partyspottr.appdir.classes.adapters;

public class CarBrands {
    public static final String[] m_CarBrands = {
            "Abarth",
            "Alfa Romeo",
            "Alpina",
            "Aston Martin",
            "Audi",
            "Austin",
            "Aixam",
            "Bentley",
            "BMW",
            "Buddy",
            "Buick",
            "Cadillac",
            "Chevrolet",
            "Chrysler",
            "Citroen",
            "Dacia",
            "Daewoo",
            "Daihatsu",
            "Datsun",
            "De Tomaso",
            "Dodge",
            "DS",
            "Ferrari",
            "Fiat",
            "Fisker",
            "Ford",
            "GMC",
            "Honda",
            "Hummer",
            "Hyundai",
            "Infiniti",
            "Isuzu",
            "Iveco",
            "Jaguar",
            "Jeep",
            "Kewet",
            "Kia",
            "Lada",
            "Lamborghini",
            "Lancia",
            "Land Rover",
            "Lexus",
            "Lincoln",
            "Lotus",
            "Maserati",
            "Maybach",
            "Mazda",
            "McLaren",
            "Mercedes-Benz",
            "Mercury",
            "MG",
            "mia electric",
            "MINI",
            "Mitsubishi",
            "Morgan",
            "Morris",
            "Nissan",
            "Oldsmobile",
            "Opel",
            "Peugeot",
            "Plymouth",
            "Pontiac",
            "Porsche",
            "Radical",
            "Renault",
            "Reva",
            "Rolls Royce",
            "Rover",
            "Seat",
            "Skoda",
            "Smart",
            "Ssangyong",
            "Subaru",
            "Suzuki",
            "Saab",
            "Tazzari",
            "Tesla",
            "Think",
            "Toyota",
            "Triumph",
            "TVR",
            "Volkswagen",
            "Volvo",
            "Willys"
    };

    public static boolean doesListContain(String brand) {
        for(String m_CarBrand : m_CarBrands) {
            if (m_CarBrand.equals(brand))
                return true;
        }

        return false;
    }
}
